In [154]:
import pandas as pd
import numpy as np
import matplotlib as plt

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [155]:
df=pd.read_csv("netflix_titles.csv")
df.head()
#df.columns

show_id     type  title           director  \
0      s1  TV Show     3%                NaN   
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   

                                         description  
0  In a future where the elite inhabit an island ...  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...  
3  In a postapocalyptic world, rag-doll robots hi...  
4  A brilliant group of students become card-coun...

In [156]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [157]:

df['listed_in'].unique

<bound method Series.unique of 0       International TV Shows, TV Dramas, TV Sci-Fi &...
1                            Dramas, International Movies
2                     Horror Movies, International Movies
3       Action & Adventure, Independent Movies, Sci-Fi...
4                                                  Dramas
                              ...                        
7782                         Dramas, International Movies
7783       Dramas, International Movies, Music & Musicals
7784    Documentaries, International Movies, Music & M...
7785                   International TV Shows, Reality TV
7786                      Documentaries, Music & Musicals
Name: listed_in, Length: 7787, dtype: object>

In [162]:
list1=[]
for l in df['listed_in']:
    l=l.split(",")
    list1.append(l[0])
df['list1']=list1
df.columns
del list

In [130]:
del df['list']
df.head()

show_id     type  title           director  \
0      s1  TV Show     3%                      
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   

                                         description                   list1  \
0  In a future where the elite inhabit an island ...  International TV Shows   
1  After a devastating earthquake hits Mexico Cit...                  Dramas   
2  When an army recruit is found dead, his fellow...           Horror Movies   
3  In a postapocalyptic world, rag-doll robots hi...      Action & Adventure   
4  A brilliant group of students become card-coun...                  Dramas   

                                       combined_feat  row_num  
0    João Miguel, Bianca Comparato, Michel Gomes,...        0  
1  Jorge Michel Grau Demián Bichir, Héctor Bonill...        1  
2  Gilbert Chan Tedd Chan, Stella Chung, Henley H...        2  
3  Shane Acker Elijah Wood, John C. Reilly, Jenni...        3  
4  Robert Luketic Jim Sturgess, Kevin Spacey, Kat...        4

In [99]:
df=df.rename(columns={'list':'list1'},inplace=False)
df.head()

show_id     type  title           director  \
0      s1  TV Show     3%                      
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   

                                         description                   list1  \
0  In a future where the elite inhabit an island ...  International TV Shows   
1  After a devastating earthquake hits Mexico Cit...                  Dramas   
2  When an army recruit is found dead, his fellow...           Horror Movies   
3  In a postapocalyptic world, rag-doll robots hi...      Action & Adventure   
4  A brilliant group of students become card-coun...                  Dramas   

                                       combined_feat  row_num  
0    João Miguel, Bianca Comparato, Michel Gomes,...        0  
1  Jorge Michel Grau Demián Bichir, Héctor Bonill...        1  
2  Gilbert Chan Tedd Chan, Stella Chung, Henley H...        2  
3  Shane Acker Elijah Wood, John C. Reilly, Jenni...        3  
4  Robert Luketic Jim Sturgess, Kevin Spacey, Kat...        4

In [131]:
features=['director','cast','rating','list1']


In [132]:
for fe in features:
    df[fe]=df[fe].fillna(' ')

In [134]:
def combine(row):
    return row['director']+" "+row['cast']+" "+row['rating']+" "+row["list1"]
df['combined_feat']=df.apply(combine,axis=1)
#print(df['combined_feat'])

In [135]:
#creating a count matrix from this combined column
cv=CountVectorizer()
count_mat=cv.fit_transform(df['combined_feat'])
#print(count_mat)


In [136]:
cosine_similarities=cosine_similarity(count_mat)

In [137]:
movie_liked='Zozo'

In [168]:
def get_title(index):
    return df[df.index==index]["title"].values[0]
def get_index(title):
    return df[df.title==title]["row_num"].values[0]

In [139]:
movie_index=get_index(movie_liked)
print(movie_index)
print(cosine_similarities)

7782
[[1.         0.2076137  0.         ... 0.27854301 0.33593551 0.24913644]
 [0.2076137  1.         0.         ... 0.2236068  0.13483997 0.2       ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.27854301 0.2236068  0.         ... 1.         0.30151134 0.67082039]
 [0.33593551 0.13483997 0.         ... 0.30151134 1.         0.26967994]
 [0.24913644 0.2        0.         ... 0.67082039 0.26967994 1.        ]]


In [165]:
similar_movies=list(enumerate(cosine_similarities[movie_index]))
sorted_similar_movies=sorted(similar_movies,key= lambda x:x[1],reverse=True)


In [169]:
#data=df.iloc[0:-1]
#data.colump
i=0
for ele in sorted_similar_movies:
    print(get_title(ele[0]))
    i=i+1
    if i>50:
        break

Zozo
Seven (Tamil)
The Light of My Eyes
That Thing Called Tadhana
(Un)Well
60 Days In
Battlefish
Bling Empire
Dating Around
Droppin' Cash: Los Angeles
Fastest Car
Haunted
Inst@famous
Jailbirds
Million Dollar Beach House
Outback Truckers
Selling Sunset
Shot in the Dark
Skin Decision: Before and After
Thackeray
Top Grier
Westside
Self Made: Inspired by the Life of Madam C.J. Walker
100 Days Of Solitude
Afflicted
Alarmoty in the Land of Fire
Alias JJ, la celebridad del mal
Aussie Gold Hunters
Camp X
Cheer
Chef's Table
Chicken Soup for the Soul's Being Dad
Christiane Amanpour: Sex & Love Around the World
Cricket Fever: Mumbai Indians
Dare to Be Wild
Dark Tourist
Deaf U
Disclosure
Explained
Fire Chasers
First and Last
Flint Town
Formula 1: Drive to Survive
Girls Incarcerated
Home Game
Immigration Nation
Kevin Hart: Don’t F**k This Up
LA Originals
Lenox Hill
Liberated: The New Sexual Revolution
Living Undocumented


In [64]:
df['row_num'] = df.reset_index().index
df.head()

show_id     type  title           director  \
0      s1  TV Show     3%                      
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   

                                         description                    list  \
0  In a future where the elite inhabit an island ...  International TV Shows   
1  After a devastating earthquake hits Mexico Cit...                  Dramas   
2  When an army recruit is found dead, his fellow...           Horror Movies   
3  In a postapocalyptic world, rag-doll robots hi...      Action & Adventure   
4  A brilliant group of students become card-coun...                  Dramas   

                                       combined_feat  row_num  
0    João Miguel, Bianca Comparato, Michel Gomes,...        0  
1  Jorge Michel Grau Demián Bichir, Héctor Bonill...        1  
2  Gilbert Chan Tedd Chan, Stella Chung, Henley H...        2  
3  Shane Acker Elijah Wood, John C. Reilly, Jenni...        3  
4  Robert Luketic Jim Sturgess, Kevin Spacey, Kat...        4